# This workflow will do a clean installation of node dependencie, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI/CD

on:
  push:
    branches:
      - "master"

jobs:
  build:
    runs-on: self-hosted
    strategy:
      matrix:
        node-version: [18.x] # Specify the Node.js version

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Create .env file
        run: |
          touch .env
          echo "${{ secrets.Trialshopy_Backend_env }}" > .env


      - name: Build and deploy
        run: tsc && pm2 restart trialshopy-backend
